export const WEATHER_DATA_PENDING = "WEATHER_DATA_PENDING";
export const CURRENT_DATA_SUCCESS = "CURRENT_DATA_SUCCESS";
export const FORECAST_DATA_SUCCESS = "FORECAST_DATA_SUCCESS";
export const WEATHER_DATA_ERROR = "WEATHER_DATA_ERROR";
export const CITY_NAME = "CITY_NAME";